version: '3'

services:
  db:
    image: mariadb:10.4
    container_name: flyway-mariadb
    ports:
      - 5505:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=flywaydb
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=1234
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
