spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:5505/flywaydb?useSSL=false&characterEncoding=utf8&autoReconnection=true
    username: flyway
    password: 1234
    validation-query: SELECT 1

  flyway:
    enabled: true

logging.level:
  org.hibernate: debug
#    type: trace
#    stat: debug


management:
  server.port: 9000
  endpoint.health.show-details: always
  endpoints.web.exposure.include: flyway, health, info, metrics, env
